### ISSUE TITLE
Remove bin/pipeline from repository

### ISSUE THREAD

**Issue by remingtonc** [cisco-ie/pipeline-gnmi#12]
Releasing the pipeline binary in the repository is pretty ugly right now. It carries a pretty large weight 40-60 MB in size. We should instead compile and post binaries in the Releases tab, and rewrite the git history to not include the pipeline binary.

@sbyx or @repenno do you have any opposition to removing the `bin/pipeline` binary?

**Comment by BenderScript** [comment]
No opposition, that's best practice not only from a weight but also from
release perspective. The binary will not work across OS, Protobuf versions
anyway, therefore when we release a binary we need to tag with it <OS
version, protobuf version> so people are clear on the environment we/CI tested
it.

**Comment by remingtonc** [comment]
Truly closed with our friend https://rtyley.github.io/bfg-repo-cleaner/

**Comment by nleiva** [comment]
Yeah, sorry for being late here. We should remove the bin folder from the repo and add binaries to the different releases.

It'd would be ideal if we can match the tag for the releases with the `appVersion` variable Chris initially used to log the version of Pipeline running.
