### ISSUE TITLE
Cleanup Test Output

### ISSUE THREAD

**Issue by BenderScript** [cisco-ie/pipeline-gnmi#20]
```make test``` Tests spill out hundreds of lines under ===A=== and ===B===, amongst others. I have no idea what these are but certainly add to the confusion. IMHO tests should output name of test and pass/fail.

**Comment by remingtonc** [comment]
This is due to #11 with a test failing, the A and B being the two outputs compared - otherwise the output is not so verbose. We can have them output to files instead on failure?
