### ISSUE TITLE
Add support for Go modules

### ISSUE THREAD

**Issue by nleiva** [cisco-ie/pipeline-gnmi#5]
We need to migrate to Go modules ([go.mod](../go.mod) and [go.sum](../go.sum)). Pipeline is currently using [Glide](https://github.com/Masterminds/glide) for dependency management which is no longer maintained. 

In order to do so, we first need to remove the changes go generate makes to jsonpb as depicted in [vendor.patch](../blob/master/vendor.patch). `EmitUInt64Unquoted` is not part of the official protobuf library, so we need to replicate the `Marshaler` struct of [github.com/golang/protobuf/jsonpb](https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L63-L84) with this field on it. "*A little copying is better than a little dependency*". 

I will first attempt to do this, before updating dependencies and bring Go 1.12 support as well.

**Comment by remingtonc** [comment]
@nleiva This appears to get more complex as we introduce modules. For example...
```
rm -rf vendor/
rm go.mod go.sum
export GO111MODULE=on
go mod init
go test -v ./
```

Errors out:
```
[pipeline-gnmi] go test -v ./                                                                                                               go-modules  ✗ ✭
# github.com/cisco-ie/pipeline-gnmi [github.com/cisco-ie/pipeline-gnmi.test]
./codec_gpb_test.go:33:3: unknown field 'EmitUInt64Unquoted' in struct literal of type jsonpb.Marshaler
./codec_gpb_test.go:39:3: unknown field 'EmitUInt64Unquoted' in struct literal of type jsonpb.Marshaler
FAIL    github.com/cisco-ie/pipeline-gnmi [build failed]
```

Fixing references:
```
# github.com/cisco-ie/pipeline-gnmi [github.com/cisco-ie/pipeline-gnmi.test]
./codec_gpb_test.go:35:3: cannot use promoted field Marshaler.EmitDefaults in struct literal of type Marshaler
./codec_gpb_test.go:36:3: cannot use promoted field Marshaler.OrigName in struct literal of type Marshaler
./codec_gpb_test.go:41:3: cannot use promoted field Marshaler.EmitDefaults in struct literal of type Marshaler
./codec_gpb_test.go:42:3: cannot use promoted field Marshaler.OrigName in struct literal of type Marshaler
FAIL    github.com/cisco-ie/pipeline-gnmi [build failed]
```

**Comment by remingtonc** [comment]
Fixed function itself but [a test is now failing](https://github.com/cisco-ie/pipeline-gnmi/blob/go-modules/codec_gpb_test.go#L110) which appears related to the unmarshaling.
Tracking in branch `go-modules`.

**Comment by remingtonc** [comment]
I am especially inclined to look at #15 with these jsonpb issues.

**Comment by nleiva** [comment]
> ```
> [pipeline-gnmi] go test -v ./                                                                                                               go-modules  ✗ ✭
> # github.com/cisco-ie/pipeline-gnmi [github.com/cisco-ie/pipeline-gnmi.test]
> ./codec_gpb_test.go:33:3: unknown field 'EmitUInt64Unquoted' in struct literal of type jsonpb.Marshaler
> ./codec_gpb_test.go:39:3: unknown field 'EmitUInt64Unquoted' in struct literal of type jsonpb.Marshaler
> FAIL    github.com/cisco-ie/pipeline-gnmi [build failed]
> ```

Yeah, [codec_gpb_test.go](https://github.com/cisco-ie/pipeline-gnmi/blob/master/codec_gpb_test.go#L17) still references to `github.com/golang/protobuf/jsonpb`. I forgot to make the changes in the test files (to reference the local jsonpb struct instead), my bad. I will fix this in the next couple of days.

> ```
> # github.com/cisco-ie/pipeline-gnmi [github.com/cisco-ie/pipeline-gnmi.test]
> ./codec_gpb_test.go:35:3: cannot use promoted field Marshaler.EmitDefaults in struct literal of type Marshaler
> ./codec_gpb_test.go:36:3: cannot use promoted field Marshaler.OrigName in struct literal of type Marshaler
> ./codec_gpb_test.go:41:3: cannot use promoted field Marshaler.EmitDefaults in struct literal of type Marshaler
> ./codec_gpb_test.go:42:3: cannot use promoted field Marshaler.OrigName in struct literal of type Marshaler
> FAIL    github.com/cisco-ie/pipeline-gnmi [build failed]
> ```

We cannot access the embedded or promoted fields in a struct literal. You either do it like you did:

```go
marshallerEmitString := &Marshaler{
	EmitUInt64Unquoted: false,
	Marshaler: jsonpb.Marshaler{
		EmitDefaults: true,
		OrigName:     true,
	},
}
```

or

```go
marshallerEmitString := Marshaler{}
marshallerEmitString.EmitUInt64Unquoted = false
marshallerEmitString.EmitDefaults = true
marshallerEmitString.OrigName = true
```

**Comment by nleiva** [comment]
> Fixed function itself but [a test is now failing](https://github.com/cisco-ie/pipeline-gnmi/blob/go-modules/codec_gpb_test.go#L110) which appears related to the unmarshaling.
> Tracking in branch `go-modules`.

I'll take a look at it.
